In [0]:
import numpy as np

###Funciones Basicas 

In [0]:
lista=[1,2,3,4]
array=np.array(lista)


In [0]:
array

array([1, 2, 3, 4])

In [0]:
lista2=[[1,2,3], [4,5,6], [7,8,9]]
array2=np.array(lista2)

In [0]:
array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

###Otras Funciones

In [0]:
# creando secuencias
array=np.arange(5)
array

array([0, 1, 2, 3, 4])

In [0]:
# le damos inicio y final
np.arange(2,9)

array([2, 3, 4, 5, 6, 7, 8])

In [0]:
# le damos inicio y final y le agremaos step
np.arange(2,20,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [0]:
#generando con CEROS
np.zeros(3)

array([0., 0., 0.])

In [0]:
#generando con CEROS
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [0]:
#generando con UNOS
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [0]:
# Generar una matriz de un unico elemento. dando un comiento y un final seguido del numero de elementos que se deben generar.

np.linspace(5,8,50)

array([5.        , 5.06122449, 5.12244898, 5.18367347, 5.24489796,
       5.30612245, 5.36734694, 5.42857143, 5.48979592, 5.55102041,
       5.6122449 , 5.67346939, 5.73469388, 5.79591837, 5.85714286,
       5.91836735, 5.97959184, 6.04081633, 6.10204082, 6.16326531,
       6.2244898 , 6.28571429, 6.34693878, 6.40816327, 6.46938776,
       6.53061224, 6.59183673, 6.65306122, 6.71428571, 6.7755102 ,
       6.83673469, 6.89795918, 6.95918367, 7.02040816, 7.08163265,
       7.14285714, 7.20408163, 7.26530612, 7.32653061, 7.3877551 ,
       7.44897959, 7.51020408, 7.57142857, 7.63265306, 7.69387755,
       7.75510204, 7.81632653, 7.87755102, 7.93877551, 8.        ])

In [0]:
#Genera una matriz cuadrada y pone numeros 1 en la mitad
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

###Numeros Aleatorios

In [0]:
np.random.rand(5) #genera uns alista siguiendo una distribucion uniforme

array([0.4563911 , 0.17731744, 0.02500406, 0.57290655, 0.39529151])

In [0]:
np.random.rand(3,4) #de dos dimenciones

array([[0.98280404, 0.50301533, 0.64574248, 0.91484692],
       [0.056113  , 0.09296062, 0.36411577, 0.6862995 ],
       [0.69392627, 0.13482676, 0.89938785, 0.81613391]])

In [0]:
np.random.randn(5) # Genera los elementos con una distribucion NORMAL     NOTA solo cambio el comando rand por randn


array([ 2.07756511, -0.10983948, -0.93999038,  0.7264174 ,  0.07104419])

In [0]:
np.random.randint(1,20)#Numeros enteros aleatorios   NOTA genera un solo numero no una lista

5

In [0]:
np.random.randint(1,20, 5)# en esta caso el 5 significa que son 5 elementos

array([19,  7, 13, 16,  2])

###Para Cambiar el Tamano de los Arrays

In [0]:
array=np.random.randint(1,10,25)
array

array([1, 1, 1, 4, 3, 4, 6, 7, 7, 9, 3, 9, 2, 4, 1, 5, 5, 7, 2, 6, 1, 1,
       3, 4, 3])

In [0]:
matriz=array.reshape(5,5)# en este caso transformamos el anterior arreglo. El tema aqui es que debe ser igual a 25 ya que son esos elementos
matriz

array([[1, 1, 1, 4, 3],
       [4, 6, 7, 7, 9],
       [3, 9, 2, 4, 1],
       [5, 5, 7, 2, 6],
       [1, 1, 3, 4, 3]])

In [0]:
array=np.random.randint(1,100,50)
array

array([59, 27, 13, 51, 39, 74, 75, 22, 45, 61, 36, 26, 18, 10, 47, 88, 15,
       85,  2, 31, 85, 67, 61,  4, 94, 86, 92, 81, 45, 88, 96, 14, 60, 61,
        3, 85, 32, 80, 11, 99, 99, 94, 11, 10, 78, 24, 46, 21, 15, 83])

In [0]:
#Averiguar el Valor Maximo y Minimo de todos los elementos Anteriores.
valor_maximo=array.max()
valor_maximo


99

In [0]:
posicion_VM=array.argmax()
posicion_VM

39

In [0]:
#Para el valos minimo.
valor_minimo=array.min()
valor_minimo

2

In [0]:
posicion_M=array.argmin()
posicion_M

18

In [0]:
#Para conseguir el valor del array uno por uno
array=np.arange(1,20,2)
array

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [0]:
# para consegui un solo valor
array[5]

11

In [0]:
# Para hacer una copia
array3=array.copy()
array3

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [0]:
array3=[[1,2,3], [4,5,6], [7,8,9]]
array3=np.array(lista2)
array3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [0]:
#para tener acceso a un valor concreto tenemos.
array3[1][1]  #Seleccionamos fila 1 columna 1

5

In [0]:
array3[0,0]  #Seleccionamos fila 1 columna 1

##Ejercicios Numpy
-
Gary


In [4]:
# List Slicing to Reverse an Array in Python
import numpy as np

def arrays(arr):
    # complete this function
    # use numpy.array
    arr = np.array(arr[ : : -1], dtype = "float")
    return(arr)

arr = input().strip().split(' ')
result = arrays(arr)
print(result)

1 2 3 4 5 6 7 8 9 10
[10.  9.  8.  7.  6.  5.  4.  3.  2.  1.]


In [25]:
# Another way to reverse an Array (Using Flip method)
import numpy as np

def arrays(arr):
    # complete this function
    # use numpy.array
    arr = np.array(arr, dtype = "float")
    arr = np.flip(arr)  #To reverse the array
    return(arr)

arr = input().strip().split(' ')
result = arrays(arr)
print(result)

1 2 3 4 5 6 7 8 9
[9. 8. 7. 6. 5. 4. 3. 2. 1.]


In [29]:
# Another way to reverse an Array (Using Flipud method)
import numpy as np

def arrays(arr):
    # complete this function
    # use numpy.array
    new_arr=np.array(arr)
    arr = np.flipud(new_arr)  #To reverse the array
    return(arr)

arr = ("J U L I A N").strip().split(' ') # string variable
result = arrays(arr)
print(result)

['N' 'A' 'I' 'L' 'U' 'J']
